<h1>Agenda<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Prezentare" data-toc-modified-id="Prezentare-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Prezentare</a></span><ul class="toc-item"><li><span><a href="#About-me" data-toc-modified-id="About-me-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>About me</a></span></li><li><span><a href="#Motivation-/-Who-are-you?" data-toc-modified-id="Motivation-/-Who-are-you?-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Motivation / Who are you?</a></span></li><li><span><a href="#Lab-Structure" data-toc-modified-id="Lab-Structure-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Lab Structure</a></span><ul class="toc-item"><li><span><a href="#Generics" data-toc-modified-id="Generics-1.3.1"><span class="toc-item-num">1.3.1&nbsp;&nbsp;</span>Generics</a></span></li><li><span><a href="#What-do-you-know-about-ML?" data-toc-modified-id="What-do-you-know-about-ML?-1.3.2"><span class="toc-item-num">1.3.2&nbsp;&nbsp;</span>What do you know about ML?</a></span></li><li><span><a href="#Ce-vom-invata?" data-toc-modified-id="Ce-vom-invata?-1.3.3"><span class="toc-item-num">1.3.3&nbsp;&nbsp;</span>Ce vom invata?</a></span></li></ul></li></ul></li><li><span><a href="#Jupyter-notebook-tutorial" data-toc-modified-id="Jupyter-notebook-tutorial-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>Jupyter notebook tutorial</a></span></li><li><span><a href="#Python" data-toc-modified-id="Python-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Python</a></span></li><li><span><a href="#Numpy" data-toc-modified-id="Numpy-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>Numpy</a></span></li><li><span><a href="#Linear-model" data-toc-modified-id="Linear-model-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>Linear model</a></span></li><li><span><a href="#Teme-pentru-acasa" data-toc-modified-id="Teme-pentru-acasa-6"><span class="toc-item-num">6&nbsp;&nbsp;</span>Teme pentru acasa</a></span><ul class="toc-item"><li><span><a href="#Install-the-workspace.zip-locally" data-toc-modified-id="Install-the-workspace.zip-locally-6.1"><span class="toc-item-num">6.1&nbsp;&nbsp;</span>Install the workspace.zip locally</a></span><ul class="toc-item"><li><span><a href="#Machine-Learning-Lab-workspace" data-toc-modified-id="Machine-Learning-Lab-workspace-6.1.1"><span class="toc-item-num">6.1.1&nbsp;&nbsp;</span>Machine Learning Lab workspace</a></span></li><li><span><a href="#Installation-of-this-project" data-toc-modified-id="Installation-of-this-project-6.1.2"><span class="toc-item-num">6.1.2&nbsp;&nbsp;</span>Installation of this project</a></span></li></ul></li><li><span><a href="#Cititi-sectiunile-despre-Python-and-Numpy" data-toc-modified-id="Cititi-sectiunile-despre-Python-and-Numpy-6.2"><span class="toc-item-num">6.2&nbsp;&nbsp;</span>Read the sections about Python, Numpy and Linear models</a></span></li><li><span><a href="#Creati-o-copie-a-acestui-laboratorrator-si-asigurati-va-toate-comenzile-functioneaza-si-intelegeti-ce-fac" data-toc-modified-id="Creati-o-copie-a-acestui-laborator-si-asigurati-va-ca-toate-comenzile-functioneaza-si-intelegeti-ce-fac-6.3"><span class="toc-item-num">6.3&nbsp;&nbsp;</span>Creati o copie a acestui laborator si asigurati-va ca toate comenzile functioneaza si intelegeti ce fac</a></span></li><li><span><a href="#Scrieti-o-clasa-Python-Point-pentru-reprezentarea-unui-punct-3D." data-toc-modified-id="Scrieti-o-clasa-Python-Point-pentru-reprezentarea-unui-punct-3D.-6.4"><span class="toc-item-num">6.4&nbsp;&nbsp;</span>Scrieti o clasa Python <code>Point</code> pentru reprezentarea unui punct 3D.</a></span></li><li><span><a href="#Rezolvati-cu-o-singura-comanda-urmatoarele-probleme-de-Numpy" data-toc-modified-id="Rezolvati-cu-o-singura-comanda-urmatoarele-probleme-de-Numpy-6.5"><span class="toc-item-num">6.5&nbsp;&nbsp;</span>Rezolvati cu o singura comanda urmatoarele probleme de Numpy</a></span></li><li><span><a href="#Ce-reprezinta-numpy-broadcasting,-dati-exemple" data-toc-modified-id="Ce-reprezinta-numpy-broadcasting,-dati-exemple-6.6"><span class="toc-item-num">6.6&nbsp;&nbsp;</span>Ce reprezinta numpy broadcasting, dati exemple</a></span></li></ul></li><li><span><a href="#Resurse" data-toc-modified-id="Resurse-7"><span class="toc-item-num">7&nbsp;&nbsp;</span>Resurse</a></span></li></ul></div>

### What do you know about ML?

Stiu, voi amesteca pe alocuri engleza cu romana, deal with it!

### Ce vom invata?

* Lab 1 - Basics: Python, Anaconda
* Lab 2 - Noțiuni matematice necesare: Numpy. Algebra liniară pentru învăţarea în automată. Statistică pentru învăţarea automată. Aplicaţii: 100_Numpy_exercises. (2h)
* Lab 3 - Învățarea supervizată: Scikit-learn: Linear regression, Logistical Regression, Vectorization methods, Pipelines. Vedere de ansamblu a algoritmilor de învăţare automată. Aplicaţii: evolutia preturilor caselor din Alba-Iulia. (2h)
* Lab 4 - Evaluarea modelelor. Keras & TensorFlow. Aplicaţii: vertebral_column_data or rossmann-store-sales datasets. (2h)
* Lab 5-6 - Metode de clasificare - Arbori de decizie (Decision Trees). Aplicaţii: RandomForests. Entropy model: MNIST classification or Iris dataset (4h)
* Lab 7 - Metode de clasificare – Învăţarea bazată pe instanţe. Metoda celor mai apropiaţi k vecini: KNN and NaiveBayes classifiers. (2h)
* Lab 8 - Învățarea în rețele neuronale: Neural Networks (MLP), Backpropagation, Stochastical Gradient Descent, RNN's. Aplicaţii: Convolutions on MNIST (2h)
* Lab 9 - Maşini cu suport vectorial SVM's. Aplicaţii. (2h)
* Lab 10 - Învățarea nesupervizată. Metode de clusterizare. Aplicaţii: Iris dataset (2h)
* Lab 11 - Tehnici folosite pentru prelucrarea imaginilor.
Image processing: Vgg16, Cat vs. Dog, Kaggle, BatchNormalisation, ReLU, MaxPooling, .., Best practices: cifar-10-python dataset. (2h)
* Lab 12 - Evaluarea activității de laborator. (2h)
..

* laboratorul X - Capsules tool, Attention, GAN's, generative models

Might change, if is to fast or irelevant

# Jupyter notebook tutorial

Ce folosesc acum se numeste *Jupyer*
    * un *IDE* online pentru Python
    * folosit pentru explorare, prototyping si data-science

Mod de folosire:
    * jurnal academic
        * reproducible
        * add only
        * comments
        * experiments
    * celule
        * 2 moduri: Y - cod, M - text
        * text - Markdown (LaTeX)
        * cod - python

I want to print some Latex formulas:

$$\sum_i(100)$$

Let's see if I can write code here

In [ ]:
import time
time.time()

I don't like so many decimal places...

I will round

In [ ]:
import numpy as np
np.round(time.time(), 3)

Much better!

Experiment if the code allways refletcts the output

In [ ]:
from random import randint
string = "this is a text"
string

I want to demonstrate that expressions without outputs do not print anything even if they are the last command in a cell.

In [5]:
string = "my_text"

The last command is displayed using an internal `display` function that, depending on the output type renders is differently (for plots it draws, for strings it prints, for animations it plays, for tables it draws a table, etc..)

In [ ]:
from IPython.display import display
display(time.time())

Test that we need print if we want to debug a nested code. In order to inspect the contents of "string" we must issue a print statement.

In [ ]:
string = "something else"
print(string)
other_var = string

Do we keep the variables context on refresh? Press F5! If we loose the context (i.e. the whole jupyter program is restarted), we expect that `other_var` will not contain any value when executing the code bellow.

In [ ]:
other_var

Since after the page refresh, `other_var` still holds the proper value, we conclude that the session is persisted between refresh. This is called a **kernel** (a python session that is kept active on the server and which retains all the current variables and state).  

Restarting a kernel: 00

Press 'H' for help

# Python

Homework: read [xkcd](http://www.xkcd.com)

* Limbaj interpretat
* Wrapper peste C++
* OOP / functional

![Python](https://imgs.xkcd.com/comics/python.png)

Like really?

In [ ]:
print("Hello world!")

Well, nu poate fi chiar totul adevarat

In [47]:
import antigravity

In [ ]:
antigravity.geohash??

Ba da, exista un modul numit "antigravity". Wtf is this??

Defining a function

In [49]:
def function(a, b):
    """
    This is a docstring of a function that does nothing
    """
    pass

Write a function that multiplies three numbers together..

In [13]:
def multiply_three_numbers(a, b, c):
    return a * b * c

In [ ]:
multiply_three_numbers(1, 2, 3)

We don't have types.. Actually we have "duck typing"... (`if it quacks like a duck and walks like a duck, then it's most likely a duck.`)

In [ ]:
type("a")

In [54]:
def f(something): # could be anything here, we'll only find out at run time
    if isinstance(something, str):
        print(ord(something[0]) + 1)
    else:
        var = 10
    var_b = 12
    return something

We can pass any values to `f`. It's unsafe, but `we're all grownups here`

In [61]:
f(1), f('a'), f(None)

98


(1, 'a', None)

Handling exceptions

In [63]:
import traceback
try:
    a = "This is a useless line"
    raise AssertionError("Trigger and exception")
except AssertionError:
    print(traceback.format_exc())

Traceback (most recent call last):
  File "/var/folders/jw/yv3564gd34d57pv9_nmtf3540000gn/T/ipykernel_40707/1712284350.py", line 4, in <module>
    raise AssertionError("Trigger and exception")
AssertionError: Trigger and exception



Classes and OOP

In [ ]:
class Complex(object):
    def __init__(self, real, imag):
        self._real = real
        self._imag = imag

    def add(self, another_complex_number):
        self._real += another_complex_number._real
        self._imag += another_complex_number._imag
        return self

a = Complex(1, 1)
b = Complex(1, 2)
a.add(b)._imag

* Notice the "self" stuff
* The last command of a cell is always displayed
* Notice we don't have the notion of "private" fields (they're all public)

Variable inspector.. (check out the target button - circle with 4 lines - in the above toolbar)

In [20]:
c = b

Example of `list comprehension` (defining a list by enumerating the elements with an embedded `for` loop)


`range` produces 1 to 10 elements, going 2 by 2, a range of numbers.

In [ ]:
a_list = [i for i in range(1, 10, 2)]
a_list

Bellow you can see an example of a `dictionary comprehension`

In [ ]:
{i:i+10 for i in range(10) }

`Set comprehension` example. Notice that unlike on dictionaries (above) we don't have the form `key: value` at the begging. It's just `i`.

Sets don't have order and only store `unique` elements.

In [ ]:
{i for i in range(10)}

Reversing a list is done with (the rather obscure) form `[::-1]`

In [ ]:
a_reversed = a_list[::-1]
a_reversed

If we say `[0:4]` it means we want all the elements between 0 and 4. This is called a `slice`

In [ ]:
a_split = a_list[0:4]
a_split

Negative indexed go back, as if the list were circular. `L[-2]` means the `second to last` element.

In [ ]:
a_list[-2]

In [ ]:
import random
r = [random.randint(0, 10) for _ in range(10)]
r

In [ ]:
sorted(r)

In [ ]:
m = dict()
n = {} # same stuff

type(m), type(n)

In [ ]:
m['a'] = 1
m[4] = 'b'

m

Dictionarele nu trebuie fie omogene in tipul de informatie pe care il retin

In [64]:
m[random] = f
m

{'a': 1,
 4: 'b',
 <module 'random' from '/Users/mihai/faculta/IA/projects/ia-lab3/env/lib/python3.13/random.py'>: <function __main__.f(something)>}

Cool? Not quite, don't get to fancy with this.

# Numpy

NumPy este pachetul fundamental necesar pentru calculul științific cu Python

   * un puternic N-dimensional array object
   * funcții sofisticate (broadcasting)
   * funcții de algebră liniară de bază
   * transformate Fourier de bază
   * capabilități sofisticate de numere aleatoare
   * instrumente pentru integrarea codului Fortran
   * instrumente pentru integrarea codului C/C++

[Numpy](https://docs.scipy.org/doc/numpy/about.html)

In [32]:
import numpy as np

In [ ]:
a = np.array([1, 2, 3])
a

In [ ]:
b = np.array([3, 4, 5])
b

In [ ]:
a + b

In [ ]:
a * b

* No loops, basically
* Highly efficient

In [ ]:
a = np.random.normal(size=(4, 5))
a

Multidimensional

In [ ]:
a * 10

In [ ]:
a.shape

* Homework: Findout about broadcasting

# Linear model - caz sintetic

Sa presupunem ca vrem sa modelam evolutia preturilor caselor din Alba-Iulia.

Stim ca exista o corelatie intre pretul unei locuinte si suprafata unui apartament in mp.  
Presupunem de asemenea ca aceasta corelatie respecta o crestere lineara.

We assume the function to be deduced is

$$y = x * 0.1 + 0.3$$


In [ ]:
# Generate some random data
x_data = np.random.rand(100).astype(np.float32)
x_data

Generate on the above function, and the previous random values, y_data

In [41]:
y_data = x_data * 0.1 + 0.3

Our goal, is, given only some (fuzzy) data points, to find the line that best describes the data

In [ ]:
noise = np.random.normal(scale=0.01, size=(100,))
noise.shape

In [ ]:
def chart(x, y):
    """
    This only prints a simple chart
    """
    %matplotlib inline
    from matplotlib import pyplot as plt
    # Plot outputs
    plt.ylabel("Pretul casei")
    plt.scatter(x, y,  color='black')
    plt.xticks(())
    plt.yticks(())
    plt.show()

chart(x_data, y_data + noise)

Telul nostru este ca din datele pe care le avem sa descoperim cele doua variable (a, b) == (0.1, 0.3) care definesc cea linia cea mai representativa

Sa presupunem ca avem o astfel de linie (stim a, b), cum putem sti cat de bine se potriveste ea cu datele?

$$y.predicted_i = a * x_i + b$$

$$ \mathcal{L}(y,x,a, b) = \dfrac{1}{M} \sum_{i=1}^{M} \sqrt{(y.true_i - y.predicted_i)^2}$$

In [ ]:
def gradient(a, b, x, y):
    y_predicted = x * a + b
    error = (y - y_predicted)
    a_ = -(1.0/len(x)) * 2 * np.sum(error * x)
    b_ = -(1.0/len(x)) * 2 * np.sum(error)
    return a_, b_

alpha is learning rate

In [ ]:
a, b = np.random.randn(2)

alpha = 0.5
for i in range(100):
    (a_, b_) = gradient(a, b, x_data, y_data)
    a = a - alpha * a_
    b = b - alpha * b_
print(a, b)

In [ ]:
def final_plot(x, y, a, b):
    %matplotlib inline
    from matplotlib import pyplot as plt

    # Plot outputs
    plt.ylabel("Pretul casei")
    plt.scatter(x, y,  color='black')
    plt.xticks(())
    plt.yticks(())
    plt.plot([0, -b/a], [b, 0])
    plt.show()

final_plot(x_data, y_data + noise, a, b)

# Teme pentru acasa

## Cititi sectiunile despre Python, Numpy !!

## Creati o copie a acestui laborator si asigurati-va ca toate comenzile functioneaza si intelegeti ce fac.

## Scrieti o clasa Python `Point` pentru reprezentarea unui punct 3D.

* scrieti metode pentru
    * calcularea distantei (euclidiene) pana la alt punct dat
    * afisarea punctului (un echivalent to_string)
* avand un punct, printati pe rand, valoarea x, y si z a sa

In [70]:
# distanta eculidiană
class Point:
    def __init__(self, x, y, z):
        self.x = x
        self.y = y
        self.z = z

    def distance(self, other):
        return np.sqrt((self.x - other.x)**2 + (self.y - other.y)**2 + (self.z - other.z)**2)
    
    def to_string(self):
        return "({}, {}, {})".format(self.x, self.y, self.z)

p1 = Point(1, 2, 3)
p2 = Point(4, 5, 6)
print(p1.to_string())
print(p2.to_string())
print(p1.distance(p2))

(1, 2, 3)
(4, 5, 6)
5.196152422706632


## Rezolvati cu o singura comanda urmatoarele probleme de Numpy

* Importati numpy (ca np) si printati versiunea
* Creati un array unidimensional cu numere de la 1 la 10
* Creati un array 3x3 cu toate valorile True
* Printati toate elementele pare dintr-un array
* Inlocuiti elementele de pe pozitiile pare dintr-un array cu valoarea -1
* Redimensionati un array de dimensiune 100 intr-unul (50, 2)

In [79]:
import numpy as np; print(np)


<module 'numpy' from '/Users/mihai/faculta/IA/projects/ia-lab3/env/lib/python3.13/site-packages/numpy/__init__.py'>


array([10,  3,  6,  7,  3,  9,  5,  9,  9,  4])

In [88]:
print(np.arange(1, 11))


[ 1  2  3  4  5  6  7  8  9 10]


In [89]:
print(np.full((3, 3), True))

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [85]:
random_array = np.random.randint(1, 100, size=20)
even_numbers = random_array[random_array % 2 == 0]
print(random_array)
print(even_numbers)


[85 38 91 20 11 76 89 80 10 22 95 98 64 89  1 24 80 44 32 61]
[38 20 76 80 10 22 98 64 24 80 44 32]


In [90]:
random_array[::2] = -1
print(random_array)

[-1 38 -1 20 -1 76 -1 80 -1 22 -1 98 -1 89 -1 24 -1 44 -1 61]


In [91]:
array_100 = np.arange(100)
reshaped_array = array_100.reshape((50, 2))
print(reshaped_array)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]
 [20 21]
 [22 23]
 [24 25]
 [26 27]
 [28 29]
 [30 31]
 [32 33]
 [34 35]
 [36 37]
 [38 39]
 [40 41]
 [42 43]
 [44 45]
 [46 47]
 [48 49]
 [50 51]
 [52 53]
 [54 55]
 [56 57]
 [58 59]
 [60 61]
 [62 63]
 [64 65]
 [66 67]
 [68 69]
 [70 71]
 [72 73]
 [74 75]
 [76 77]
 [78 79]
 [80 81]
 [82 83]
 [84 85]
 [86 87]
 [88 89]
 [90 91]
 [92 93]
 [94 95]
 [96 97]
 [98 99]]


## Ce reprezinta numpy broadcasting, dati exemple

este o metodă care permite operațiilor pe array-uri de dimensiuni diferite să fie efectuate fără a necesita duplicarea datelor. Broadcasting-ul extinde automat array-urile mai mici pentru a se potrivi cu dimensiunile array-urilor mai mari, astfel încât operațiile să poată fi efectuate eficient.

### Exemplu 1: Adunarea unui scalar la un array


In [ ]:
a = np.array([1, 2, 3])
b = 2
result = a + b

### Exemplu 2: Adunarea unui vector la un array 2D


In [92]:

a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([1, 2, 3])
result = a + b
print(result)

[[2 4 6]
 [5 7 9]]


# Resurse

[Jupyter Notbook tutorial](https://www.datacamp.com/community/tutorials/tutorial-jupyter-notebook)  
[Python tutorial](https://www.stavros.io/tutorials/python/)  
[Tutorial numpy](https://cs231n.github.io/python-numpy-tutorial/)  

